### PR TITLE
Fixing detection of priviledged protection level of SEED_VAULT_IMPL permission

### LINKED ISSUE #115: Detection of privileged SEED_VAULT_IMPL permission fails
Seed Vault SDK clients fail to check if a real seed vault implementation exists on the host OS.

### PR DESCRIPTION
**Pull request by J909**
Currently, the detection of the privileged protection level of `com.solanamobile.seedvault.SEED_VAULT_IMPL` always fails.
This change queries the protection level of this permission to detect its implementation on the system image. 
Fixes #115

### CODE REVIEW

**Review by sdlaver — APPROVED** [review]

File: seedvault/src/main/java/com/solanamobile/seedvault/SeedVault.java [hunk 1]
```diff
@@ -49,7 +51,7 @@ public static boolean isAvailable(@NonNull Context context, boolean allowSimulat
 
         for (PermissionInfo permission : pi.permissions) {
             if (WalletContractV1.PERMISSION_SEED_VAULT_IMPL.equals(permission.name) &&
-                    ((permission.flags & PermissionInfo.PROTECTION_FLAG_PRIVILEGED) != 0)) {
+                    ((permission.getProtectionFlags() & PROTECTION_FLAG_PRIVILEGED) != 0)) {
```
Comment (sdlaver) [inline seedvault/src/main/java/com/solanamobile/seedvault/SeedVault.java:54]: @J909 https://github.com/solana-mobile/seed-vault-sdk/actions/runs/4171225225/jobs/7231733394#step:5:589

Comment (sdlaver) [reply seedvault/src/main/java/com/solanamobile/seedvault/SeedVault.java:54]:
```
/home/runner/work/seed-vault-sdk/seed-vault-sdk/seedvault/src/main/java/com/solanamobile/seedvault/SeedVault.java:54: Error: Call requires API level 28 (current min is 23): android.content.pm.PermissionInfo#getProtectionFlags [NewApi]
                    ((permission.getProtectionFlags() & PROTECTION_FLAG_PRIVILEGED) != 0)) {
                                 ~~~~~~~~~~~~~~~~~~
```

Comment (sdlaver) [reply seedvault/src/main/java/com/solanamobile/seedvault/SeedVault.java:54]: Can probably just use the `protectionLevel` field directly: https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/content/pm/PermissionInfo.java;l=361

**Review by sdlaver — APPROVED** [review]
